### ISSUE TITLE
Error creating schedule. Conflict with another plugin.

### ISSUE THREAD

**Issue by st-mcd** [panlatent/schedule#10]
Hi, I am hoping to use your plugin to schedule a daily event but when I attempt to create a new schedule I get the error below. It relates to the ether/simplemap plugin and one of it's integrations for the FeedMe plugin. If the class does not exist should this fail gracefully?

```
yii\base\ErrorException: Class 'craft\feedme\base\Field' not found in /var/www/html/vendor/ether/simplemap/src/integrations/feedme/FeedMeMaps.php:25
Stack trace:
#0 /var/www/html/vendor/yiisoft/yii2/base/ErrorHandler.php(0): craft\web\ErrorHandler->handleFatalError()
#1 /var/www/html/vendor/panlatent/schedule/src/helpers/ClassHelper.php(78): panlatent\schedule\helpers\ClassHelper->unknown()
#2 /var/www/html/vendor/panlatent/schedule/src/schedules/Event.php(103): panlatent\schedule\helpers\ClassHelper::findClasses()
#3 /var/www/html/vendor/panlatent/schedule/src/schedules/Event.php(69): panlatent\schedule\schedules\Event->_getClassSuggestions()
#4 /var/www/html/vendor/yiisoft/yii2/base/Component.php(139): panlatent\schedule\schedules\Event->getSettingsHtml()
#5 /var/www/html/vendor/craftcms/cms/src/helpers/Template.php(74): panlatent\schedule\schedules\Event->__get()
#6 /var/www/html/storage/runtime/compiled_templates/31/316a35bec9f5558d5fb8811db1a46985b43f7fff801b33e7b84ff6d5ce964da2.php(161): craft\helpers\Template::attribute()
#7 /var/www/html/vendor/twig/twig/src/Template.php(184): __TwigTemplate_c7cd661207ed39920ef71ea0714709c8f86e2c1b429d9cff3c309f9a67d97615->block_content()
#8 /var/www/html/storage/runtime/compiled_templates/2b/2b4490a3c13d4dcd392555844a97edad173b13714a67068b9d6f9ece811a1d77.php(439): __TwigTemplate_ae071c0b250a4b6ca99dc6d1d6df5ee988d913468db89d5ff7be57e02ef35a4d->displayBlock()
#9 /var/www/html/vendor/twig/twig/src/Template.php(184): __TwigTemplate_ae071c0b250a4b6ca99dc6d1d6df5ee988d913468db89d5ff7be57e02ef35a4d->block_main()
#10 /var/www/html/storage/runtime/compiled_templates/2b/2b4490a3c13d4dcd392555844a97edad173b13714a67068b9d6f9ece811a1d77.php(304): __TwigTemplate_ae071c0b250a4b6ca99dc6d1d6df5ee988d913468db89d5ff7be57e02ef35a4d->displayBlock()
#11 /var/www/html/vendor/twig/twig/src/Template.php(184): __TwigTemplate_ae071c0b250a4b6ca99dc6d1d6df5ee988d913468db89d5ff7be57e02ef35a4d->block_body()
#12 /var/www/html/storage/runtime/compiled_templates/35/35a86cf81ac5314231807b48c6b90b345ec7aaca743f4fb9c607833dfeab016b.php(85): __TwigTemplate_45907578813fb777bea75ee6a6ada6fe59849e23f1a844c74f55104c05ac0619->displayBlock()
#13 /var/www/html/vendor/twig/twig/src/Template.php(407): __TwigTemplate_45907578813fb777bea75ee6a6ada6fe59849e23f1a844c74f55104c05ac0619->doDisplay()
#14 /var/www/html/vendor/twig/twig/src/Template.php(380): __TwigTemplate_45907578813fb777bea75ee6a6ada6fe59849e23f1a844c74f55104c05ac0619->displayWithErrorHandling()
#15 /var/www/html/storage/runtime/compiled_templates/87/877c89b76c6cbdcb66352fcb9e690bc5cd0d0a0746893361869f1771f45d75b3.php(56): __TwigTemplate_45907578813fb777bea75ee6a6ada6fe59849e23f1a844c74f55104c05ac0619->display()
#16 /var/www/html/vendor/twig/twig/src/Template.php(407): __TwigTemplate_8bfcf43c8feeeb5dd63bbb5f6a05aebaae80e6923acc67df25cff96b200a0673->doDisplay()
#17 /var/www/html/vendor/twig/twig/src/Template.php(380): __TwigTemplate_8bfcf43c8feeeb5dd63bbb5f6a05aebaae80e6923acc67df25cff96b200a0673->displayWithErrorHandling()
#18 /var/www/html/storage/runtime/compiled_templates/2b/2b4490a3c13d4dcd392555844a97edad173b13714a67068b9d6f9ece811a1d77.php(154): __TwigTemplate_8bfcf43c8feeeb5dd63bbb5f6a05aebaae80e6923acc67df25cff96b200a0673->display()
#19 /var/www/html/vendor/twig/twig/src/Template.php(407): __TwigTemplate_ae071c0b250a4b6ca99dc6d1d6df5ee988d913468db89d5ff7be57e02ef35a4d->doDisplay()
#20 /var/www/html/vendor/twig/twig/src/Template.php(380): __TwigTemplate_ae071c0b250a4b6ca99dc6d1d6df5ee988d913468db89d5ff7be57e02ef35a4d->displayWithErrorHandling()
#21 /var/www/html/storage/runtime/compiled_templates/31/316a35bec9f5558d5fb8811db1a46985b43f7fff801b33e7b84ff6d5ce964da2.php(57): __TwigTemplate_ae071c0b250a4b6ca99dc6d1d6df5ee988d913468db89d5ff7be57e02ef35a4d->display()
#22 /var/www/html/vendor/twig/twig/src/Template.php(407): __TwigTemplate_c7cd661207ed39920ef71ea0714709c8f86e2c1b429d9cff3c309f9a67d97615->doDisplay()
#23 /var/www/html/vendor/twig/twig/src/Template.php(380): __TwigTemplate_c7cd661207ed39920ef71ea0714709c8f86e2c1b429d9cff3c309f9a67d97615->displayWithErrorHandling()
#24 /var/www/html/vendor/twig/twig/src/Template.php(392): __TwigTemplate_c7cd661207ed39920ef71ea0714709c8f86e2c1b429d9cff3c309f9a67d97615->display()
#25 /var/www/html/vendor/twig/twig/src/TemplateWrapper.php(45): __TwigTemplate_c7cd661207ed39920ef71ea0714709c8f86e2c1b429d9cff3c309f9a67d97615->render()
#26 /var/www/html/vendor/twig/twig/src/Environment.php(318): Twig\TemplateWrapper->render()
#27 /var/www/html/vendor/craftcms/cms/src/web/View.php(391): craft\web\twig\Environment->render()
#28 /var/www/html/vendor/craftcms/cms/src/web/View.php(452): craft\web\View->renderTemplate()
#29 /var/www/html/vendor/craftcms/cms/src/web/Controller.php(243): craft\web\View->renderPageTemplate()
#30 /var/www/html/vendor/panlatent/schedule/src/controllers/SchedulesController.php(154): panlatent\schedule\controllers\SchedulesController->renderTemplate()
#31 /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php(57): panlatent\schedule\controllers\SchedulesController->actionEditSchedule()
#32 /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php(57): ::call_user_func_array:{/var/www/html/vendor/yiisoft/yii2/base/InlineAction.php:57}()
#33 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(180): yii\base\InlineAction->runWithParams()
#34 /var/www/html/vendor/craftcms/cms/src/web/Controller.php(181): panlatent\schedule\controllers\SchedulesController->runAction()
#35 /var/www/html/vendor/yiisoft/yii2/base/Module.php(528): panlatent\schedule\controllers\SchedulesController->runAction()
#36 /var/www/html/vendor/craftcms/cms/src/web/Application.php(294): craft\web\Application->runAction()
#37 /var/www/html/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction()
#38 /var/www/html/vendor/craftcms/cms/src/web/Application.php(279): craft\web\Application->handleRequest()
#39 /var/www/html/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest()
#40 /var/www/html/web/index.php(21): craft\web\Application->run()
#41 {main}
```

**Comment by panlatent** [comment]
This should be caused by class auto-completion.

I may need more information and take some time to solve it.
