### ISSUE TITLE
RuntimeException when creating new schedule

### ISSUE THREAD

**Issue by iamkeir** [panlatent/schedule#8]
Hi there :) Having installed your app, when I try to create a new schedule I receive a Craft error:
`RuntimeException: The HOME or COMPOSER_HOME environment variable must be set for composer to run correctly`

Any ideas? I don't have any issues with Composer, Craft or other plugins... Thanks.

### Full report
```
RuntimeException: The HOME or COMPOSER_HOME environment variable must be set for composer to run correctly in /Users/iamkeir/Sites/ben/build/vendor/composer/composer/src/Composer/Factory.php:648
Stack trace:
#0 /Users/iamkeir/Sites/ben/build/vendor/composer/composer/src/Composer/Factory.php(69): Composer\Factory::getUserDir()
#1 /Users/iamkeir/Sites/ben/build/vendor/composer/composer/src/Composer/Factory.php(160): Composer\Factory::getHomeDir()
#2 /Users/iamkeir/Sites/ben/build/vendor/composer/composer/src/Composer/Factory.php(303): Composer\Factory::createConfig(Object(Composer\IO\NullIO), '/Users/iamkeir/...')
#3 /Users/iamkeir/Sites/ben/build/vendor/panlatent/schedule/src/helpers/ClassHelper.php(52): Composer\Factory->createComposer(Object(Composer\IO\NullIO), Array)
#4 /Users/iamkeir/Sites/ben/build/vendor/panlatent/schedule/src/schedules/Event.php(103): panlatent\schedule\helpers\ClassHelper::findClasses()
#5 /Users/iamkeir/Sites/ben/build/vendor/panlatent/schedule/src/schedules/Event.php(69): panlatent\schedule\schedules\Event->_getClassSuggestions()
#6 /Users/iamkeir/Sites/ben/build/vendor/yiisoft/yii2/base/Component.php(139): panlatent\schedule\schedules\Event->getSettingsHtml()
#7 /Users/iamkeir/Sites/ben/build/vendor/craftcms/cms/src/helpers/Template.php(89): yii\base\Component->__get('settingsHtml')
#8 /Users/iamkeir/Sites/ben/build/storage/runtime/compiled_templates/3c/3c79e8afd96d3b1257a0a95364ef59004fb44c1f3c18b08c0b164978bccfe7e0.php(164): craft\helpers\Template::attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(panlatent\schedule\schedules\Event), 'settingsHtml', Array)
#9 /Users/iamkeir/Sites/ben/build/vendor/twig/twig/src/Template.php(184): __TwigTemplate_3e57447eb45dbde95517095b799d6ce28851dcf2e765bd3f932c6569df19e518->block_content(Array, Array)
#10 /Users/iamkeir/Sites/ben/build/storage/runtime/compiled_templates/82/8266e8a470accad67868929c36bb0409feb708496f343ac5a282929c9e70ca5a.php(727): Twig\Template->displayBlock('content', Array, Array)
#11 /Users/iamkeir/Sites/ben/build/vendor/twig/twig/src/Template.php(184): __TwigTemplate_202b44ac9d554c55f49304257cee7d06e890a7eb4ac49356a880a2b4cf3390a5->block_main(Array, Array)
#12 /Users/iamkeir/Sites/ben/build/storage/runtime/compiled_templates/82/8266e8a470accad67868929c36bb0409feb708496f343ac5a282929c9e70ca5a.php(576): Twig\Template->displayBlock('main', Array, Array)
#13 /Users/iamkeir/Sites/ben/build/vendor/twig/twig/src/Template.php(184): __TwigTemplate_202b44ac9d554c55f49304257cee7d06e890a7eb4ac49356a880a2b4cf3390a5->block_body(Array, Array)
#14 /Users/iamkeir/Sites/ben/build/storage/runtime/compiled_templates/97/97f885eeec896c06cfeae354224d2663ef43197a6b1e61061ec80cf1cef9ec85.php(75): Twig\Template->displayBlock('body', Array, Array)
#15 /Users/iamkeir/Sites/ben/build/vendor/twig/twig/src/Template.php(407): __TwigTemplate_6aa451c8c76e9b2e5cdf3cdeef914a8ff8f581a1f29db00d1cc1f131efb6fd4d->doDisplay(Array, Array)
#16 /Users/iamkeir/Sites/ben/build/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#17 /Users/iamkeir/Sites/ben/build/storage/runtime/compiled_templates/12/128240ac9d49437d9e8ee94436e13b031b7c10f5b45dd23063b2a52e03752180.php(56): Twig\Template->display(Array, Array)
#18 /Users/iamkeir/Sites/ben/build/vendor/twig/twig/src/Template.php(407): __TwigTemplate_ce5f42e443a28710d82968b6dbf04f4284089c457f1c11ad16966293e9a9b524->doDisplay(Array, Array)
#19 /Users/iamkeir/Sites/ben/build/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#20 /Users/iamkeir/Sites/ben/build/storage/runtime/compiled_templates/82/8266e8a470accad67868929c36bb0409feb708496f343ac5a282929c9e70ca5a.php(118): Twig\Template->display(Array, Array)
#21 /Users/iamkeir/Sites/ben/build/vendor/twig/twig/src/Template.php(407): __TwigTemplate_202b44ac9d554c55f49304257cee7d06e890a7eb4ac49356a880a2b4cf3390a5->doDisplay(Array, Array)
#22 /Users/iamkeir/Sites/ben/build/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#23 /Users/iamkeir/Sites/ben/build/storage/runtime/compiled_templates/3c/3c79e8afd96d3b1257a0a95364ef59004fb44c1f3c18b08c0b164978bccfe7e0.php(58): Twig\Template->display(Array, Array)
#24 /Users/iamkeir/Sites/ben/build/vendor/twig/twig/src/Template.php(407): __TwigTemplate_3e57447eb45dbde95517095b799d6ce28851dcf2e765bd3f932c6569df19e518->doDisplay(Array, Array)
#25 /Users/iamkeir/Sites/ben/build/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#26 /Users/iamkeir/Sites/ben/build/vendor/twig/twig/src/Template.php(392): Twig\Template->display(Array)
#27 /Users/iamkeir/Sites/ben/build/vendor/twig/twig/src/TemplateWrapper.php(45): Twig\Template->render(Array, Array)
#28 /Users/iamkeir/Sites/ben/build/vendor/twig/twig/src/Environment.php(318): Twig\TemplateWrapper->render(Array)
#29 /Users/iamkeir/Sites/ben/build/vendor/craftcms/cms/src/web/View.php(344): Twig\Environment->render('schedule/_edit', Array)
#30 /Users/iamkeir/Sites/ben/build/vendor/craftcms/cms/src/web/View.php(393): craft\web\View->renderTemplate('schedule/_edit', Array)
#31 /Users/iamkeir/Sites/ben/build/vendor/craftcms/cms/src/web/Controller.php(243): craft\web\View->renderPageTemplate('schedule/_edit', Array)
#32 /Users/iamkeir/Sites/ben/build/vendor/panlatent/schedule/src/controllers/SchedulesController.php(154): craft\web\Controller->renderTemplate('schedule/_edit', Array)
#33 [internal function]: panlatent\schedule\controllers\SchedulesController->actionEditSchedule(NULL, Object(panlatent\schedule\schedules\Console))
#34 /Users/iamkeir/Sites/ben/build/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#35 /Users/iamkeir/Sites/ben/build/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#36 /Users/iamkeir/Sites/ben/build/vendor/craftcms/cms/src/web/Controller.php(187): yii\base\Controller->runAction('edit-schedule', Array)
#37 /Users/iamkeir/Sites/ben/build/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('edit-schedule', Array)
#38 /Users/iamkeir/Sites/ben/build/vendor/craftcms/cms/src/web/Application.php(299): yii\base\Module->runAction('schedule/schedu...', Array)
#39 /Users/iamkeir/Sites/ben/build/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('schedule/schedu...', Array)
#40 /Users/iamkeir/Sites/ben/build/vendor/craftcms/cms/src/web/Application.php(284): yii\web\Application->handleRequest(Object(craft\web\Request))
#41 /Users/iamkeir/Sites/ben/build/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#42 /Users/iamkeir/Sites/ben/build/web/index.php(21): yii\base\Application->run()
#43 {main}
```

**Comment by panlatent** [comment]
Thank you! This problem is caused by the Composer exception caused by your loss of the HOME environment variable. You can fix this in the environment. I am considering whether to deal with this problem in the plugin, so the code will not be updated for the time being.

**Comment by iamkeir** [comment]
@panlatent thanks for getting back to me so quickly :) Do you know how to fix this issue with Composer? I've been googling but struggling to find a fix. Was curious as to why only this plugin was causing it though. However, if it is a Composer config issue, I wouldn't say it is a fix needed in the plugin - just a nice-to-have. Thanks and feel free to close :)

**Comment by panlatent** [comment]
> @panlatent thanks for getting back to me so quickly :) Do you know how to fix this issue with Composer? I've been googling but struggling to find a fix. Was curious as to why only this plugin was causing it though. However, if it is a Composer config issue, I wouldn't say it is a fix needed in the plugin - just a nice-to-have. Thanks and feel free to close :)

The plug-in includes auto-completion of class names. This function is implemented with Composer. You can refer to these error messages.
