### ISSUE TITLE
Schedule Update Failure

### ISSUE THREAD

**Issue by mightycitizen** [panlatent/schedule#9]
I am trying to update Schedule and it's failing and seems due to one of Schedule's migrations failing. I'm running Craft 3.3.19 and Schedule 0.2.1.2 and am trying to update to Schedule 0.2.2. The MySQL errors are below. Let me know if I can provide any more information. Thanks!

```
Database Exception: SQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP 'schedules_groupId_handle_unq_idx'; check that column/key exists
The SQL being executed was: DROP INDEX schedules_groupId_handle_unq_idx ON tasbo_schedules

Migration: panlatent\schedule\migrations\m191010_060704_fix_shedules_handle_unqidx
```

Output:

```
> drop index schedules_groupId_handle_unq_idx on {{%schedules}} ...Exception: SQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP 'schedules_groupId_handle_unq_idx'; check that column/key exists
The SQL being executed was: DROP INDEX schedules_groupId_handle_unq_idx ON tasbo_schedules (/home/309251.cloudwaysapps.com/edtvyvycza/private_html/vendor/yiisoft/yii2/db/Schema.php:674)
#0 /home/309251.cloudwaysapps.com/edtvyvycza/private_html/vendor/yiisoft/yii2/db/Command.php(1295): yii\db\Schema->convertException(Object(PDOException), 'DROP INDEX sch...')
#1 /home/309251.cloudwaysapps.com/edtvyvycza/private_html/vendor/yiisoft/yii2/db/Command.php(1091): yii\db\Command->internalExecute('DROP INDEX sch...')
#2 /home/309251.cloudwaysapps.com/edtvyvycza/private_html/vendor/yiisoft/yii2/db/Migration.php(507): yii\db\Command->execute()
#3 /home/309251.cloudwaysapps.com/edtvyvycza/private_html/vendor/panlatent/schedule/src/migrations/m191010_060704_fix_shedules_handle_unqidx.php(17): yii\db\Migration->dropIndex('schedules_group...', '{{%schedules}}')
#4 /home/309251.cloudwaysapps.com/edtvyvycza/private_html/vendor/craftcms/cms/src/db/Migration.php(58): panlatent\schedule\migrations\m191010_060704_fix_shedules_handle_unqidx->safeUp()
#5 /home/309251.cloudwaysapps.com/edtvyvycza/private_html/vendor/craftcms/cms/src/db/MigrationManager.php(239): craft\db\Migration->up(true)
#6 /home/309251.cloudwaysapps.com/edtvyvycza/private_html/vendor/craftcms/cms/src/db/MigrationManager.php(159): craft\db\MigrationManager->migrateUp(Object(panlatent\schedule\migrations\m191010_060704_fix_shedules_handle_unqidx))
#7 /home/309251.cloudwaysapps.com/edtvyvycza/private_html/vendor/craftcms/cms/src/services/Updates.php(238): craft\db\MigrationManager->up()
#8 /home/309251.cloudwaysapps.com/edtvyvycza/private_html/vendor/craftcms/cms/src/controllers/BaseUpdaterController.php(522): craft\services\Updates->runMigrations(Array)
#9 /home/309251.cloudwaysapps.com/edtvyvycza/private_html/vendor/craftcms/cms/src/controllers/UpdaterController.php(209): craft\controllers\BaseUpdaterController->runMigrations(Array, 'restore-db')
#10 [internal function]: craft\controllers\UpdaterController->actionMigrate()
#11 /home/309251.cloudwaysapps.com/edtvyvycza/private_html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#12 /home/309251.cloudwaysapps.com/edtvyvycza/private_html/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#13 /home/309251.cloudwaysapps.com/edtvyvycza/private_html/vendor/craftcms/cms/src/web/Controller.php(187): yii\base\Controller->runAction('migrate', Array)
#14 /home/309251.cloudwaysapps.com/edtvyvycza/private_html/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('migrate', Array)
#15 /home/309251.cloudwaysapps.com/edtvyvycza/private_html/vendor/craftcms/cms/src/web/Application.php(299): yii\base\Module->runAction('updater/migrate', Array)
#16 /home/309251.cloudwaysapps.com/edtvyvycza/private_html/vendor/craftcms/cms/src/web/Application.php(652): craft\web\Application->runAction('updater/migrate')
#17 /home/309251.cloudwaysapps.com/edtvyvycza/private_html/vendor/craftcms/cms/src/web/Application.php(251): craft\web\Application->_processUpdateLogic(Object(craft\web\Request))
#18 /home/309251.cloudwaysapps.com/edtvyvycza/private_html/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#19 /home/309251.cloudwaysapps.com/edtvyvycza/public_html/index.php(21): yii\base\Application->run()
#20 {main}
```

**Comment by mightycitizen** [comment]
@panlatent Have you had a chance to look into this? Thanks!

**Comment by panlatent** [comment]
> @panlatent Have you had a chance to look into this? Thanks!

I'm very sorry, I was busy with other things before. I am going to start solving it now

**Comment by panlatent** [comment]
This migration action deleted an index. For unknown reasons, there is no such index in your table. Please add `schedules_groupId_handle_unq_idx` table index before performing the migration to ensure smooth execution of the migration.

There is only one report, if more reports appear, I will fix.
